### ISSUE TITLE
Config Stage issue

### ISSUE THREAD

**Issue by Harpkan** [Appdynamics/AppDash#43]
Stuck at the config stage (adding my login information and it fails during testing the connection)
![screen](https://user-images.githubusercontent.com/46991588/51665446-c8b81a80-1f89-11e9-9956-ed4d54629502.png)

Error details:

g {name: "RequestError", message: "Error: connect ETIMEDOUT 192.230.74.156:443", cause: Error: connect ETIMEDOUT 192.230.74.156:443
    at Object._errnoException (util.js:1024:11)
    at _…, error: Error: connect ETIMEDOUT 192.230.74.156:443
    at Object._errnoException (util.js:1024:11)
    at _…, options: {…}, …}cause: Error: connect ETIMEDOUT 192.230.74.156:443
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)error: Error: connect ETIMEDOUT 192.230.74.156:443
   at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)message: "Error: connect ETIMEDOUT 192.230.74.156:443"name: "RequestError"options: {url: "https://equifax.saas.appdynamics.com/controller/rest/applications?output=json", port: 80, auth: {…}, transform: undefined, callback: ƒ, …}response: undefinedstack: "RequestError: Error: connect ETIMEDOUT 192.230.74.156:443↵    at new g (file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:140:13221)↵    at O.callback (file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:140:15268)↵    at O.A.callback.E.callback [as _callback] (file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:140:14714)↵    at E._callback.E.callback.E.callback (file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:140:40589)↵    at emitOne (events.js:116:13)↵    at O.emit (events.js:211:7)↵    at O.onRequestError (file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:140:49506)↵    at emitOne (events.js:116:13)↵    at ClientRequest.emit (events.js:211:7)↵    at TLSSocket.socketErrorListener (_http_client.js:387:9)↵    at emitOne (events.js:116:13)↵    at TLSSocket.emit (events.js:211:7)↵    at emitErrorNT (internal/streams/destroy.js:64:8)↵    at _combinedTickCallback (internal/process/next_tick.js:138:11)↵    at process._tickCallback (internal/process/next_tick.js:180:9)↵From previous event:↵    at T.P [as _captureStackTrace] (file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:17:38528)↵    at T._resolveFromExecutor (file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:17:68178)↵    at new T (file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:17:61416)↵    at O.init (file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:140:14558)↵    at O.A.request.Request.init (file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:140:12717)↵    at new O (file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:140:39902)↵    at B (file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:140:18071)↵    at file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:1:8807048↵    at Generator.next (<anonymous>)↵    at g (file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:1:8806828)↵    at file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:1:8806969↵    at T.E._execute (file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:17:37994)↵    at T._resolveFromExecutor (file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:17:68235)↵    at new T (file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:17:61416)↵    at file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:1:8806763↵    at E.getApps (file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:1:8807280)↵    at C (file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:1:8835302)↵    at C.next (<anonymous>)↵    at g (file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:1:8835479)↵    at file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:1:8835618↵    at new Promise (<anonymous>)↵    at g (file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:1:8835416)↵    at E.default (file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:1:8835651)↵    at E (file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:1:10168)↵    at E.next (<anonymous>)↵    at g (file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:1:10372)↵    at file:///C:/Users/hxk87/AppData/Local/Programs/electron-react-boilerplate/resources/app.asar/dist/renderer.prod.js:1:10511↵    at new Promise (<anonymous>)"__stackCleaned__: true__proto__: Error

**Comment by sys13** [comment]
Hi Harpkan, Can you please send me login details so I can test? daniel.arrizza@appdynamics.com

**Comment by Harpkan** [comment]
Hi Daniel, I able to connect now from my home laptop, I guess the proxy at my Work place was stopping me earlier. Thank you for a quick response. 
This tool is fantastic!
